In [7]:
import pandas as pd
import csv

In [9]:
HighSchool2017_data = pd.read_csv("C:/Users/May 2018/Desktop/SMU Bootcamp Doc/GroupProject/Team6/County_Data_Download_4yr_2017.csv")
HighSchool2017_data.head()

FileNotFoundError: File b'C:/Users/May 2018/Desktop/SMU Bootcamp Doc/GroupProject/Team6/County_Data_Download_4yr_2017.csv' does not exist

In [3]:
HighSchool2017_dfw = HighSchool2017_data.loc[HighSchool2017_data['CNTYNAME'].isin(['DENTON COUNTY','COLLIN COUNTY','HUNT COUNTY','ROCKWALL COUNTY','KAUFMAN COUNTY','ELLIS COUNTY','JOHNSON COUNTY','DALLAS COUNTY','SOMMERVILLE COUNTY','HOOD','PARKER COUNTY','WISE COUNTY','TARRANT COUNTY'])]
HighSchool2017_dfw = pd.DataFrame(HighSchool2017_dfw)
HighSchool2017_dfw_df = HighSchool2017_dfw.filter(items=['CNTYNAME','CNTY_ALLR_GRAD','CNTY_AAR_GRAD','CNTY_ASR_GRAD',
                                                         'CNTY_HSR_GRAD','CNTY_MUR_GRAD','CNTY_NAR_GRAD','CNTY_PIR_GRAD',
                                                         'CNTY_WHR_GRAD'])
HighSchool2017_dfw_df.rename(columns={'CNTYNAME':'County Name','CNTY_ALLR_GRAD':'All Students','CNTY_AAR_GRAD':'African American',
                             'CNTY_ASR_GRAD':'Asian','CNTY_HSR_GRAD':'Hispanic','CNTY_MUR_GRAD':'Multiracial','CNTY_NAR_GRAD':'American Indian',
                                      'CNTY_PIR_GRAD':'Pacific Islander','CNTY_WHR_GRAD':'White'},inplace=True)
HighSchool2017_dfw_df

,County Name,All Students,African American,Asian,Hispanic,Multiracial,American Indian,Pacific Islander,White
42,COLLIN COUNTY,96.8,95.8,98.6,94.4,98.6,96.8,96.4,97.4
56,DALLAS COUNTY,84.0,80.8,93.5,84,81.3,74.4,92.5,87.1
60,DENTON COUNTY,94.5,92.1,96.7,91.4,96.7,95.7,100,95.9
69,ELLIS COUNTY,93.1,92.5,100,92,90.2,87.5,100,94.0
115,HUNT COUNTY,93.7,91.7,100,95.2,100,92.3,100,93.0
125,JOHNSON COUNTY,94.7,95.7,91.7,95.2,92.2,100,100,94.4
128,KAUFMAN COUNTY,95.5,97,93.8,94.4,95.1,80,100,95.8
181,PARKER COUNTY,96.3,97.1,100,97,97.1,100,100,96.1
196,ROCKWALL COUNTY,97.0,96.9,97.6,95.2,100,100,100,97.4
217,TARRANT COUNTY,90.5,87.7,94.1,88.2,92.1,90,95.6,93.9
246,WISE COUNTY,96.6,100,100,95.8,100,100,.,96.9

In [7]:
TexasCrime2017_data = pd.read_csv("C:/Data Science Bootcamp/Data Science Boot Camp/Team6/County_crime_data_2017.csv")
TexasCrime2017_data.head()

       Agency Name Number of Incidents
0  ANDERSON COUNTY                 268
1   ANDERSON CO SO                 105
2     PALESTINE PD                 151
3     FRANKSTON PD                  12
4   ANDREWS COUNTY                  42

In [10]:
DFWCrime2017 = TexasCrime2017_data.loc[TexasCrime2017_data['Agency Name'].isin(['DENTON COUNTY','COLLIN COUNTY','HUNT COUNTY','ROCKWALL COUNTY','KAUFMAN COUNTY','ELLIS COUNTY','JOHNSON COUNTY','DALLAS COUNTY','SOMMERVILLE COUNTY','HOOD','PARKER COUNTY','WISE COUNTY','TARRANT COUNTY'])]
# Changed county names to match Census naming convention 
County Names = ['Collin County, Texas','Dallas County, Texas','Denton County, Texas','Ellis County, Texas','Hunt County, Texas','Johnson County, Texas','Kaufman County, Texas','Parker County, Texas','Rockwall County, Texas','Tarrant County, Texas','Wise County, Texas']
DFWCrime2017_df = pd.DataFrame(DFWCrime2017)
DFWCrime2017_df.columns = ["County Names", "Family Violence Incidents"]
DFWCrime2017_df

          County Name Family Violence Incidents
210     COLLIN COUNTY                     3,227
264     DALLAS COUNTY                    21,928
304     DENTON COUNTY                     2,249
356      ELLIS COUNTY                       623
603       HUNT COUNTY                       634
639    JOHNSON COUNTY                       925
657    KAUFMAN COUNTY                       682
855     PARKER COUNTY                       520
906   ROCKWALL COUNTY                       382
978    TARRANT COUNTY                    13,827
1135      WISE COUNTY                       176

In [9]:
HSGradCrime_2017_df = pd.merge(HighSchool2017_dfw_df,DFWCrime2017_df,on='County Name')
HSGradCrime_2017_df

,County Name,All Students,African American,Asian,Hispanic,Multiracial,American Indian,Pacific Islander,White,Family Violence Incidents
0,COLLIN COUNTY,96.8,95.8,98.6,94.4,98.6,96.8,96.4,97.4,"3,227"
1,DALLAS COUNTY,84.0,80.8,93.5,84,81.3,74.4,92.5,87.1,"21,928"
2,DENTON COUNTY,94.5,92.1,96.7,91.4,96.7,95.7,100,95.9,"2,249"
3,ELLIS COUNTY,93.1,92.5,100,92,90.2,87.5,100,94.0,623
4,HUNT COUNTY,93.7,91.7,100,95.2,100,92.3,100,93.0,634
5,JOHNSON COUNTY,94.7,95.7,91.7,95.2,92.2,100,100,94.4,925
6,KAUFMAN COUNTY,95.5,97,93.8,94.4,95.1,80,100,95.8,682
7,PARKER COUNTY,96.3,97.1,100,97,97.1,100,100,96.1,520
8,ROCKWALL COUNTY,97.0,96.9,97.6,95.2,100,100,100,97.4,382
9,TARRANT COUNTY,90.5,87.7,94.1,88.2,92.1,90,95.6,93.9,"13,827"
10,WISE COUNTY,96.6,100,100,95.8,100,100,.,96.9,176